### ISSUE TITLE
Shims are failing on Windows with .exe suffix as python scripts

### ISSUE THREAD

**Issue by Tremeschin** [konstin/rustup-pypi#5]
Hey, not sure what has changed on Windows OS' side, but it seems to be ignoring the shebangs (if they were ever a thing there) and executing the shims as a standard .exe file following some users of mine reports, causing errors like these:

**PowerShell:**
```
❯ uvx --from rustup cargo
error: Failed to spawn: `cargo`
  Caused by: This version of %1 is not compatible with the version of Windows you're running.
Check your computer's system information and then contact the software publisher. (os error 216)
```

**cmd**: A popup modal dialog:

<img alt="Image" src="https://github.com/user-attachments/assets/da4a97b6-1c36-4e03-8dd2-e4da1e3a13e1" />

<br>
<br>

I'm 100% positive they worked at least two weeks ago as .exes, but no code has changed ever since, which is weird.

No issues on Linux/macOS as they _know_ it's a python script via contents.

### Potential solution

Easy way out is doing something similar to my reference repo for issue #2 defining the entry points in [`[project.scripts]`](https://github.com/TremeschinArchive/rustup-pypi-shims/blob/main/pyproject.toml#L11) and letting the package manager create files. On lin/mac they are basically `name = "package.module:main"` -> `from package.module import main; main()` as `venv/bin/name` metaprogrammed python scripts, but for windows, files like black.exe, gradio.exe seems to be native platform executables.

Also, instead of a unique file per shim, bundling a main script with multiple functions works much nicer 🙂

**Comment by Tremeschin** [comment]
I just pushed an initial prototype on how we can tag a hatchling wheel for different platforms + seamlessly include binary artifacts at https://github.com/BrokenSource/Rustman. Will be improving it in the next hours/days, please take a look!

**Comment by CNSeniorious000** [comment]
@Tremeschin The [`rustman/shims.py`](https://github.com/BrokenSource/Rustman/blob/b93580ae297497360824806986f9c45a4e3387ee/rustman/shims.py#L26-L66) you wrote can be much simplier with a [module-level `__getattr__`](https://peps.python.org/pep-0562/#specification), which is more pythonic:

```py
# import ...

def _shim(proxy: str) -> NoReturn: ...

def __getattr__(cmd: str):
    return lambda: _shim(cmd.replace("_", "-"))

def __dir__():
    return ["rustup_init", "cargo", "cargo_clippy", "cargo_fmt", ...]
```

And update [`pyproject.toml`](https://github.com/BrokenSource/Rustman/blob/b93580ae297497360824806986f9c45a4e3387ee/pyproject.toml#L9-L23) to:

```toml
[project.scripts]
rustup-init   = "rustman.shims:rustup_init"
cargo         = "rustman.shims:cargo"
cargo-clippy  = "rustman.shims:cargo_clippy"
cargo-fmt     = "rustman.shims:cargo_fmt"
cargo-miri    = "rustman.shims:cargo_miri"
clippy-driver = "rustman.shims:clippy_driver"
rls           = "rustman.shims:rls"
# ...
```

Everything will work just fine and there will be less boilerplate.

**Comment by Tremeschin** [comment]
Super interesting @CNSeniorious000 , will definitely play with that!

I was trying to come up with a hybrid method to call them via projects scripts under NoReturn or passing argv parameters in regular code, might need the boilerplate anyways for basic users type hinting, perhaps a `functools.partial` could do the trick with one line per shim!

On a tangent note, the OS/Arch abstractions feel like a short-lived experiment. Manually defining rust-triples :: wheel-tag and hoping one covers all platforms will simplify it even further, rip sdists

**Comment by konstin** [comment]
Thanks for the report! I've switched to `project.scripts`, I still have to test on Windows to confirm that the approach is working

**Comment by CNSeniorious000** [comment]
Not yet. Currently shims are correct but `_shim` still fail to find the executable here:

https://github.com/konstin/rustup-pypi/blob/27bb6314ccacaa96b4c2ead50ba7f22b716496e7/src/rustup/shim.py#L15

That's because on Windows it is `rustup.exe` instead of `rustup`.

<details><summary>traceback</summary>
<p>

```sh
> uvx --from git+https://github.com/konstin/rustup-pypi cargo

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\.uv_cache\archive-v0\zFgpE4F-RKACjiI2ZC5Mg\Scripts\cargo.exe\__main__.py", line 10, in <module>
    sys.exit(cargo())
             ~~~~~^^
  File "C:\.uv_cache\archive-v0\zFgpE4F-RKACjiI2ZC5Mg\Lib\site-packages\rustup\shim.py", line 28, in cargo
    _shim("cargo")
    ~~~~~^^^^^^^^^
  File "C:\.uv_cache\archive-v0\zFgpE4F-RKACjiI2ZC5Mg\Lib\site-packages\rustup\shim.py", line 17, in _shim
    raise RuntimeError(f"rustup binary does not exist: {rustup}")
RuntimeError: rustup binary does not exist: C:\.uv_cache\archive-v0\zFgpE4F-RKACjiI2ZC5Mg\Scripts\rustup
```

</p>
</details>

**Comment by konstin** [comment]
I've fixed the Windows code and added a smoke test in CI.
